"""Shared column list for a scraped product row — used by both scraper.py (to build
rows) and db.py (to define the `products` table and build upsert SQL). Kept in its own
module so scraper.py and db.py can each import it without importing each other."""

PREFERRED_COLUMNS = [
    "scraped_at",
    "source_url",
    "page_type",
    "category_slug",
    "shop_slug",
    "url",
    "product_id",
    "variant_id",
    "name",
    "slug",
    "sku",
    "shop_sku",
    "seller_sku",
    "brand",
    "brand_id",
    "category",
    "category_id",
    "seller_name",
    "seller_id",
    "shop_name",
    "shop_url",
    "price",
    "original_price",
    "discount_percentage",
    "currency",
    "stock",
    "availability",
    "rating",
    "rating_count",
    "warranty",
    "warranty_period",
    "return_option",
    "free_shipping",
    "is_cartup_fast",
    "is_best_seller",
    "highlight",
    "box_items",
    "description",
    "images",
    "thumbnail",
    "video_url",
    "package_weight_kg",
    "package_height_cm",
    "package_width_cm",
    "package_length_cm",
    "variants_json",
    "attributes_json",
    "product_json",
]
